package mybatis.dao;

import java.util.List;
import mybatis.pojo.Cat;
import mybatis.pojo.CatExample;
import org.apache.ibatis.annotations.Param;

public interface CatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    int countByExample(CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    int deleteByExample(CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    int insert(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    int insertSelective(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    List<Cat> selectByExample(CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    Cat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    int updateByExampleSelective(@Param("record") Cat record, @Param("example") CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    int updateByExample(@Param("record") Cat record, @Param("example") CatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    int updateByPrimaryKeySelective(Cat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_cat
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    int updateByPrimaryKey(Cat record);
}