package mybatis.dao;

import java.util.List;
import mybatis.model.Pet;
import mybatis.model.PetExample;
import org.apache.ibatis.annotations.Param;

public interface PetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Tue Jan 08 17:54:46 CST 2013
     */
    int countByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Tue Jan 08 17:54:46 CST 2013
     */
    int deleteByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Tue Jan 08 17:54:46 CST 2013
     */
    int insert(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Tue Jan 08 17:54:46 CST 2013
     */
    int insertSelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Tue Jan 08 17:54:46 CST 2013
     */
    List<Pet> selectByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Tue Jan 08 17:54:46 CST 2013
     */
    int updateByExampleSelective(@Param("record") Pet record, @Param("example") PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet
     *
     * @mbggenerated Tue Jan 08 17:54:46 CST 2013
     */
    int updateByExample(@Param("record") Pet record, @Param("example") PetExample example);
}