package com.webservice.xfire.wsdl.helloWebService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version:
 * 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* HelloWebService service = new HelloWebService();
* HelloWebServicePortType portType = service.getHelloWebServiceHttpPort();
* portType.sayHello(...);
* </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "HelloWebService", targetNamespace = "http://xfire.webservice.com", wsdlLocation = "http://3w.eztravel.com.tw:8080/XFireDemo/services/HelloWebService?wsdl")
public class HelloWebService extends Service {

  private final static URL HELLOWEBSERVICE_WSDL_LOCATION;
  private final static Logger logger = Logger
      .getLogger(com.webservice.xfire.wsdl.helloWebService.HelloWebService.class.getName());

  static {
    URL url = null;
    try {
      URL baseUrl;
      baseUrl = com.webservice.xfire.wsdl.helloWebService.HelloWebService.class.getResource(".");
      url =
          new URL(baseUrl, "http://3w.eztravel.com.tw:8080/XFireDemo/services/HelloWebService?wsdl");
    } catch (MalformedURLException e) {
      logger
          .warning("Failed to create URL for the wsdl Location: 'http://3w.eztravel.com.tw:8080/XFireDemo/services/HelloWebService?wsdl', retrying as a local file");
      logger.warning(e.getMessage());
    }
    HELLOWEBSERVICE_WSDL_LOCATION = url;
  }

  public HelloWebService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public HelloWebService() {
    super(HELLOWEBSERVICE_WSDL_LOCATION,
        new QName("http://xfire.webservice.com", "HelloWebService"));
  }

  /**
   * 
   * @return returns HelloWebServicePortType
   */
  @WebEndpoint(name = "HelloWebServiceHttpPort")
  public HelloWebServicePortType getHelloWebServiceHttpPort() {
    return super.getPort(new QName("http://xfire.webservice.com", "HelloWebServiceHttpPort"),
        HelloWebServicePortType.class);
  }

}
