package com.webservice.xfire.wsdl.helloWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version:
 * 2.0
 * 
 */
@WebService(name = "HelloWebServicePortType", targetNamespace = "http://xfire.webservice.com")
public interface HelloWebServicePortType {


  /**
   * 
   * @param in0
   * @return returns java.lang.String
   */
  @WebMethod
  @WebResult(name = "out", targetNamespace = "http://xfire.webservice.com")
  @RequestWrapper(localName = "sayHello", targetNamespace = "http://xfire.webservice.com", className = "com.webservice.xfire.wsdl.helloWebService.SayHello")
  @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://xfire.webservice.com", className = "com.webservice.xfire.wsdl.helloWebService.SayHelloResponse")
  public String sayHello(
      @WebParam(name = "in0", targetNamespace = "http://xfire.webservice.com") String in0);

}
