package com.webservice.xfire;

// Generated by MyEclipse

/*
 * HelloWebServiceDTHP 的實作類別
 */
public class HelloWebServiceDTHPImpl implements IHelloWebServiceDTHP {

  public String sayHello(String message) {
    return message;
  } // end sayHello

}
