package com.webservice.xfire;

// Generated by MyEclipse

/*
 *  HelloWebServiceSignature 的介面
 */
public interface IHelloWebServiceSignature {

  // 定義服務方法
  public String sayHello(String message);

}
