package mybatis.pojo;

import java.util.Date;

public class Cat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cat.id
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cat.createDate
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_cat.name
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cat.id
     *
     * @return the value of tb_cat.id
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cat.id
     *
     * @param id the value for tb_cat.id
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cat.createDate
     *
     * @return the value of tb_cat.createDate
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cat.createDate
     *
     * @param createdate the value for tb_cat.createDate
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_cat.name
     *
     * @return the value of tb_cat.name
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_cat.name
     *
     * @param name the value for tb_cat.name
     *
     * @mbggenerated Mon Nov 25 15:35:11 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}